apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-backend
  name: {{ .Release.Name }}-backend
spec:
  ports:
  - name: service-http
    port: 3000
    targetPort: http
  selector:
    app: {{ .Release.Name }}-backend
  type: ClusterIP