apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-frontend
  name: {{ .Release.Name }}-frontend
spec:
  ports:
  - name: service-http
    port: 3001
    targetPort: http
  selector:
    app: {{ .Release.Name }}-frontend
  type: ClusterIP